# Generated by Django 2.2.5 on 2020-01-10 21:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_auto_20191215_1210'),
        ('students', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='StudentGroup',
            new_name='Student',
        ),
    ]
