# Generated by Django 2.2.5 on 2019-09-21 01:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='teacherprofile',
            name='area',
        ),
        migrations.AlterField(
            model_name='adminprofile',
            name='staf',
            field=models.CharField(choices=[('NN', 'Ninguna'), ('OT', 'Oficina Técnica'), ('S', 'Secretaria'), ('C', 'Coordinador')], default='NN', max_length=5),
        ),
    ]
