# Generated by Django 2.2.5 on 2019-10-19 17:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='adminprofile',
            name='staff',
            field=models.CharField(max_length=5),
        ),
    ]
