# Generated by Django 2.2.5 on 2019-09-21 02:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_auto_20190920_2033'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='clientprofile',
            name='area',
        ),
    ]
