# Generated by Django 2.2.5 on 2019-10-23 01:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_auto_20191019_1202'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='clientprofile',
            name='reference',
        ),
    ]
