# Generated by Django 2.2.5 on 2019-09-21 03:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_remove_clientprofile_area'),
    ]

    operations = [
        migrations.RenameField(
            model_name='adminprofile',
            old_name='staf',
            new_name='staff',
        ),
    ]
