# Generated by Django 2.2.5 on 2019-10-23 16:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_auto_20191022_2117'),
    ]

    operations = [
        migrations.AlterField(
            model_name='adminprofile',
            name='staff',
            field=models.CharField(max_length=30),
        ),
    ]
