# Generated by Django 2.2.5 on 2019-10-23 23:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_auto_20191023_1155'),
    ]

    operations = [
        migrations.AddField(
            model_name='adminprofile',
            name='title',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='teacherprofile',
            name='title',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
