# Generated by Django 2.2.5 on 2019-12-15 16:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_auto_20191023_1854'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='StudentProfile',
            new_name='GroupProfile',
        ),
        migrations.RenameField(
            model_name='user',
            old_name='is_student',
            new_name='is_group',
        ),
    ]
