# Generated by Django 2.2.5 on 2019-12-15 17:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_auto_20191215_1125'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='groupprofile',
            name='codigo',
        ),
        migrations.RemoveField(
            model_name='groupprofile',
            name='dni',
        ),
        migrations.AddField(
            model_name='groupprofile',
            name='group_name',
            field=models.CharField(default='G', max_length=64, unique=True),
            preserve_default=False,
        ),
    ]
