# Generated by Django 2.2.5 on 2019-11-06 03:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tests_soil', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='limit',
            name='layer',
            field=models.CharField(choices=[('UNO', 'Estrato 1'), ('DOS', 'Estrato 2'), ('TRES', 'Estrato 3'), ('CUATRO', 'Estrato 4')], default='', max_length=6),
            preserve_default=False,
        ),
    ]
