# Generated by Django 2.2.5 on 2020-03-27 18:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tests_soil', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='globalmesh',
            name='tamiz_N_200',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='globalmesh',
            name='tamiz_N_4',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='globalmesh',
            name='tamiz_fondo',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='granulometricglobal',
            name='max_size',
            field=models.CharField(choices=[('4"', '4 inch'), ('3"', '3 inch'), ('2 1/2"', '2 1/2 inch'), ('2"', '2 inch'), ('1 1/2"', '1 1/2 inch'), ('1"', '1 inch'), ('3/4"', '3/4 inch'), ('1/2"', '1/2 inch'), ('3/8"', '3/8 inch'), ('# 4', 'Nº 4')], default='2"', max_length=7),
        ),
    ]
