# Generated by Django 2.2.5 on 2020-06-13 15:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tests_soil', '0002_auto_20200327_1313'),
    ]

    operations = [
        migrations.AlterField(
            model_name='moisturematerial',
            name='material',
            field=models.CharField(choices=[('GRAVA', 'Gravas'), ('FINO', 'Finos')], max_length=6),
        ),
    ]
