# Generated by Django 2.2.5 on 2019-11-06 04:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tests_soil', '0003_liquid'),
    ]

    operations = [
        migrations.CreateModel(
            name='Platic',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bowl', models.IntegerField()),
                ('bowl_weight', models.FloatField()),
                ('wet_weight', models.FloatField()),
                ('dry_weight', models.FloatField()),
                ('water_weight', models.FloatField(editable=False)),
                ('material_weight', models.FloatField(editable=False)),
                ('moisture', models.FloatField(editable=False)),
                ('limit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tests_soil.Limit')),
            ],
        ),
    ]
