# Generated by Django 2.2.5 on 2020-06-16 16:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tests_soil', '0004_auto_20200615_2043'),
    ]

    operations = [
        migrations.AddField(
            model_name='proctorm',
            name='correction_check',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='proctorm',
            name='process',
            field=models.CharField(choices=[('PROCEDIMIENTO_A', 'Procedimiento A'), ('PROCEDIMIENTO_B', 'Procedimiento B'), ('PROCEDIMIENTO_C', 'Procedimiento C')], default='PROCEDIMIENTO_A', max_length=15),
        ),
        migrations.AddField(
            model_name='proctorm',
            name='saturation_check',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='proctorm',
            name='material',
            field=models.CharField(max_length=100),
        ),
    ]
