# Generated by Django 2.2.5 on 2019-11-06 23:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('equipments', '0001_initial'),
        ('tools', '0001_initial'),
        ('tests_soil', '0004_platic'),
    ]

    operations = [
        migrations.AddField(
            model_name='liquid',
            name='equipment',
            field=models.ManyToManyField(to='equipments.Equip'),
        ),
        migrations.AddField(
            model_name='liquid',
            name='tool',
            field=models.ManyToManyField(to='tools.Tool'),
        ),
    ]
