# Generated by Django 2.2.5 on 2019-11-08 02:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('equipments', '0001_initial'),
        ('tools', '0001_initial'),
        ('tests_soil', '0005_auto_20191106_1835'),
    ]

    operations = [
        migrations.AddField(
            model_name='platic',
            name='equipment',
            field=models.ManyToManyField(to='equipments.Equip'),
        ),
        migrations.AddField(
            model_name='platic',
            name='tool',
            field=models.ManyToManyField(to='tools.Tool'),
        ),
    ]
