# Generated by Django 2.2.5 on 2020-06-20 03:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tests_soil', '0005_auto_20200616_1143'),
    ]

    operations = [
        migrations.AddField(
            model_name='specificgravity',
            name='pass_check',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='specificgravity',
            name='reteained_check',
            field=models.BooleanField(default=False),
        ),
    ]
