# Generated by Django 2.2.5 on 2020-06-29 16:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tests_soil', '0006_auto_20200619_2239'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ContentMoistureCarbure',
        ),
    ]
