# Generated by Django 2.2.5 on 2020-06-29 17:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tests_soil', '0007_delete_contentmoisturecarbure'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sandcone',
            name='opt_moisture',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='sandcone',
            name='weight_dry_max',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
