# Generated by Django 2.2.5 on 2020-06-29 17:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tests_soil', '0008_auto_20200629_1203'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sandcone',
            name='element_side',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='sandcone',
            name='layer',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='sandcone',
            name='progressive_sector',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='sandcone',
            name='section_level',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
