# Generated by Django 2.2.5 on 2019-11-14 15:57

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tests_soil', '0008_equiv_equivalent'),
    ]

    operations = [
        migrations.AlterField(
            model_name='equiv',
            name='out_dec_time',
            field=models.TimeField(default=datetime.time(0, 0)),
        ),
        migrations.AlterField(
            model_name='equiv',
            name='out_sat_time',
            field=models.TimeField(default=datetime.time(0, 0)),
        ),
        migrations.AlterField(
            model_name='equiv',
            name='start_dec_time',
            field=models.TimeField(default=datetime.time(0, 0)),
        ),
        migrations.AlterField(
            model_name='equiv',
            name='start_sat_time',
            field=models.TimeField(default=datetime.time(0, 0)),
        ),
    ]
