# Generated by Django 2.2.5 on 2020-07-05 16:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tests_soil', '0009_auto_20200629_1217'),
    ]

    operations = [
        migrations.AddField(
            model_name='proctorm',
            name='gs',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
