# Generated by Django 2.2.5 on 2020-07-05 18:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tests_soil', '0010_proctorm_gs'),
    ]

    operations = [
        migrations.AddField(
            model_name='correction',
            name='frac_extrad_weight',
            field=models.FloatField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='correction',
            name='frac_fina_weight',
            field=models.FloatField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='correction',
            name='frac_gruesa_weight',
            field=models.FloatField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='correction',
            name='g_frac_fina_gruesa',
            field=models.FloatField(default=1, editable=False),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='correction',
            name='g_sp_frac_fina',
            field=models.FloatField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='correction',
            name='g_sp_global',
            field=models.FloatField(default=1, editable=False),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='correction',
            name='p_sp_frac_extrad',
            field=models.FloatField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='correction',
            name='p_sp_frac_gruesa',
            field=models.FloatField(default=1),
            preserve_default=False,
        ),
    ]
