# Generated by Django 2.2.5 on 2019-11-17 18:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tools', '0001_initial'),
        ('equipments', '0001_initial'),
        ('tests_soil', '0010_densitywetdry_proctorm'),
    ]

    operations = [
        migrations.CreateModel(
            name='Saturation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('frac_extrad_weight', models.FloatField()),
                ('frac_gruesa_weight', models.FloatField()),
                ('frac_fina_weight', models.FloatField()),
                ('p_sp_frac_extrad', models.FloatField()),
                ('p_sp_frac_gruesa', models.FloatField()),
                ('g_sp_frac_fina', models.FloatField()),
                ('g_frac_fina_gruesa', models.FloatField(editable=False)),
                ('g_sp_global', models.FloatField(editable=False)),
                ('equipment', models.ManyToManyField(to='equipments.Equip')),
                ('proctor_m', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tests_soil.ProctorM')),
                ('tool', models.ManyToManyField(to='tools.Tool')),
            ],
        ),
    ]
