# Generated by Django 2.2.5 on 2020-07-05 18:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tests_soil', '0011_auto_20200705_1331'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Saturation',
        ),
    ]
