# Generated by Django 2.2.5 on 2019-11-18 00:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('equipments', '0001_initial'),
        ('tools', '0001_initial'),
        ('tests_soil', '0011_saturation'),
    ]

    operations = [
        migrations.CreateModel(
            name='Correction',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bowl_weight', models.IntegerField()),
                ('wet_weight', models.FloatField()),
                ('dry_weight', models.FloatField()),
                ('water_weight', models.FloatField(editable=False)),
                ('material_weight', models.FloatField(editable=False)),
                ('moisture', models.FloatField(editable=False)),
                ('equipment', models.ManyToManyField(to='equipments.Equip')),
                ('proctor_m', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tests_soil.ProctorM')),
                ('tool', models.ManyToManyField(to='tools.Tool')),
            ],
        ),
    ]
