# Generated by Django 2.2.5 on 2019-11-18 00:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tests_soil', '0012_correction'),
    ]

    operations = [
        migrations.AlterField(
            model_name='correction',
            name='bowl_weight',
            field=models.FloatField(),
        ),
    ]
