# Generated by Django 2.2.5 on 2019-11-18 13:16

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('reference_person', '0007_auto_20191023_1837'),
        ('construction', '0003_remove_construction_reference'),
        ('course', '0002_auto_20191018_2305'),
        ('tools', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('equipments', '0001_initial'),
        ('tests_soil', '0013_auto_20191117_1942'),
    ]

    operations = [
        migrations.CreateModel(
            name='MoistureContent',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='Contenido Humedad', max_length=50)),
                ('material', models.CharField(max_length=50)),
                ('quarry', models.CharField(max_length=50)),
                ('code', models.CharField(editable=False, max_length=255, unique=True)),
                ('sampling_date', models.DateField()),
                ('done_date', models.DateField(default=datetime.datetime.now)),
                ('dilate', models.IntegerField(editable=False)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('construction', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='construction.Construction')),
                ('course', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='course.Course')),
                ('equipment', models.ManyToManyField(to='equipments.Equip')),
                ('reference_person', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='reference_person.ReferencePerson')),
                ('tool', models.ManyToManyField(to='tools.Tool')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='MoistureMaterial',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('material', models.CharField(choices=[('SUELO', 'Suelos'), ('ARENA', 'Arenas'), ('GRAVA', 'Gravas'), ('FINO', 'Finos')], max_length=6)),
                ('bowl_weight', models.FloatField()),
                ('wet_weight', models.FloatField()),
                ('dry_weight', models.FloatField()),
                ('water_weight', models.FloatField(editable=False)),
                ('material_weight', models.FloatField(editable=False)),
                ('moisture', models.FloatField(editable=False)),
                ('equipment', models.ManyToManyField(to='equipments.Equip')),
                ('proctor_m', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tests_soil.MoistureContent')),
                ('tool', models.ManyToManyField(to='tools.Tool')),
            ],
        ),
    ]
