# Generated by Django 2.2.5 on 2019-11-18 14:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tests_soil', '0014_moisturecontent_moisturematerial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='moisturematerial',
            old_name='proctor_m',
            new_name='moisture_content',
        ),
    ]
