# Generated by Django 2.2.5 on 2019-11-19 12:29

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0002_auto_20191018_2305'),
        ('construction', '0003_remove_construction_reference'),
        ('tools', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('reference_person', '0007_auto_20191023_1837'),
        ('equipments', '0001_initial'),
        ('tests_soil', '0015_auto_20191118_0943'),
    ]

    operations = [
        migrations.CreateModel(
            name='SpecificGravity',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='Gravedad Especifica', max_length=50)),
                ('material', models.CharField(max_length=50)),
                ('quarry', models.CharField(max_length=50)),
                ('code', models.CharField(editable=False, max_length=255, unique=True)),
                ('sampling_date', models.DateField()),
                ('done_date', models.DateField(default=datetime.datetime.now)),
                ('dilate', models.IntegerField(editable=False)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('construction', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='construction.Construction')),
                ('course', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='course.Course')),
                ('equipment', models.ManyToManyField(to='equipments.Equip')),
                ('reference_person', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='reference_person.ReferencePerson')),
                ('tool', models.ManyToManyField(to='tools.Tool')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='FractionRetained',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('material_retained', models.FloatField()),
                ('temperature_23', models.FloatField(default=22.0)),
                ('saturated_sample', models.FloatField()),
                ('w_basket_water', models.FloatField()),
                ('w_basket_water_sample', models.FloatField()),
                ('w_bowl', models.FloatField()),
                ('w_bowl_sample', models.FloatField()),
                ('w_sample_dry', models.FloatField(editable=False)),
                ('w_sample_sat_water', models.FloatField(editable=False)),
                ('specific_grav_mass', models.FloatField(editable=False)),
                ('specific_grav_mass_sss', models.FloatField(editable=False)),
                ('apparent_spe_gravity', models.FloatField(editable=False)),
                ('coefficient_water', models.FloatField(default=0.99979)),
                ('specific_mass_weight', models.FloatField(editable=False)),
                ('specific_mass_weight_sss', models.FloatField(editable=False)),
                ('specific_mass_weight_app', models.FloatField(editable=False)),
                ('absorption', models.FloatField(editable=False)),
                ('equipment', models.ManyToManyField(to='equipments.Equip')),
                ('specific_gravity', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tests_soil.SpecificGravity')),
                ('tool', models.ManyToManyField(to='tools.Tool')),
            ],
        ),
        migrations.CreateModel(
            name='FractionPass',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('material_pass', models.FloatField()),
                ('temperature', models.FloatField(default=21.0)),
                ('water_density', models.FloatField(default=0.99799)),
                ('pycnometer_volume', models.FloatField()),
                ('pycnometer_mass', models.FloatField()),
                ('mass_pycnometer_water', models.FloatField(editable=False)),
                ('sample_mass', models.FloatField()),
                ('mass_pyc_w_sample', models.FloatField()),
                ('mass_bowl', models.FloatField()),
                ('mass_bowl_sample', models.FloatField()),
                ('mass_dry_sample', models.FloatField(editable=False)),
                ('gravity_specific', models.FloatField(editable=False)),
                ('coefficient_water', models.FloatField(default=0.99979)),
                ('gravity_specific_real', models.FloatField(editable=False)),
                ('equipment', models.ManyToManyField(to='equipments.Equip')),
                ('specific_gravity', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tests_soil.SpecificGravity')),
                ('tool', models.ManyToManyField(to='tools.Tool')),
            ],
        ),
    ]
