# Generated by Django 2.2.5 on 2019-11-22 22:25

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('equipments', '0001_initial'),
        ('tools', '0001_initial'),
        ('course', '0002_auto_20191018_2305'),
        ('reference_person', '0007_auto_20191023_1837'),
        ('construction', '0003_remove_construction_reference'),
        ('tests_soil', '0016_fractionpass_fractionretained_specificgravity'),
    ]

    operations = [
        migrations.CreateModel(
            name='GranulometricGlobal',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='Granulometria Tamizado Gloval', max_length=50)),
                ('quarry', models.CharField(max_length=50)),
                ('layer', models.CharField(choices=[('UNO', 'Estrato 1'), ('DOS', 'Estrato 2'), ('TRES', 'Estrato 3'), ('CUATRO', 'Estrato 4')], max_length=6)),
                ('code', models.CharField(editable=False, max_length=255, unique=True)),
                ('sampling_date', models.DateField()),
                ('done_date', models.DateField(default=datetime.datetime.now)),
                ('dilate', models.IntegerField(editable=False)),
                ('tamiz_1_1o2', models.FloatField(blank=True, null=True)),
                ('tamiz_1', models.FloatField(blank=True, null=True)),
                ('tamiz_3o4', models.FloatField(blank=True, null=True)),
                ('tamiz_1o2', models.FloatField(blank=True, null=True)),
                ('tamiz_3o8', models.FloatField(blank=True, null=True)),
                ('tamiz_4', models.FloatField(blank=True, null=True)),
                ('tamiz_10', models.FloatField(blank=True, null=True)),
                ('tamiz_20', models.FloatField(blank=True, null=True)),
                ('tamiz_40', models.FloatField(blank=True, null=True)),
                ('tamiz_60', models.FloatField(blank=True, null=True)),
                ('tamiz_100', models.FloatField(blank=True, null=True)),
                ('tamiz_200', models.FloatField(blank=True, null=True)),
                ('tamiz_fondo', models.FloatField(blank=True, null=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('construction', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='construction.Construction')),
                ('course', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='course.Course')),
                ('equipment', models.ManyToManyField(to='equipments.Equip')),
                ('reference_person', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='reference_person.ReferencePerson')),
                ('tool', models.ManyToManyField(to='tools.Tool')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
