# Generated by Django 2.2.5 on 2019-11-26 17:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tests_soil', '0018_contentmoisture_contentmoisturecarbure_correctionsandcone_humiddensity_sandcone'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sandcone',
            name='material',
        ),
    ]
