# Generated by Django 2.2.5 on 2019-11-27 04:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tests_soil', '0019_remove_sandcone_material'),
    ]

    operations = [
        migrations.AlterField(
            model_name='humiddensity',
            name='volume_material_extracted',
            field=models.FloatField(editable=False),
        ),
    ]
