# Generated by Django 2.2.5 on 2020-01-05 03:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('equipments', '0001_initial'),
        ('tools', '0001_initial'),
        ('tests_soil', '0021_auto_20200104_2159'),
    ]

    operations = [
        migrations.CreateModel(
            name='GlobalMesh',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tamiz_3', models.FloatField(blank=True, null=True)),
                ('tamiz_2_1o2', models.FloatField(blank=True, null=True)),
                ('tamiz_2', models.FloatField(blank=True, null=True)),
                ('tamiz_1_1o2', models.FloatField(blank=True, null=True)),
                ('tamiz_1', models.FloatField(blank=True, null=True)),
                ('tamiz_3o4', models.FloatField(blank=True, null=True)),
                ('tamiz_1o2', models.FloatField(blank=True, null=True)),
                ('tamiz_3o8', models.FloatField(blank=True, null=True)),
                ('tamiz_4', models.FloatField(blank=True, null=True)),
                ('tamiz_8', models.FloatField(blank=True, null=True)),
                ('tamiz_10', models.FloatField(blank=True, null=True)),
                ('tamiz_16', models.FloatField(blank=True, null=True)),
                ('tamiz_20', models.FloatField(blank=True, null=True)),
                ('tamiz_30', models.FloatField(blank=True, null=True)),
                ('tamiz_40', models.FloatField(blank=True, null=True)),
                ('tamiz_50', models.FloatField(blank=True, null=True)),
                ('tamiz_60', models.FloatField(blank=True, null=True)),
                ('tamiz_80', models.FloatField(blank=True, null=True)),
                ('tamiz_100', models.FloatField(blank=True, null=True)),
                ('tamiz_140', models.FloatField(blank=True, null=True)),
                ('tamiz_200', models.FloatField(blank=True, null=True)),
                ('tamiz_fondo', models.FloatField(blank=True, null=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('equipment', models.ManyToManyField(to='equipments.Equip')),
                ('granulometric_global', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tests_soil.GranulometricGlobal')),
                ('tool', models.ManyToManyField(to='tools.Tool')),
            ],
        ),
    ]
