# Generated by Django 2.2.5 on 2020-01-07 03:12

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('equipments', '0001_initial'),
        ('tools', '0001_initial'),
        ('tests_soil', '0024_auto_20200106_2209'),
    ]

    operations = [
        migrations.AddField(
            model_name='globalmesh',
            name='created',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='globalmesh',
            name='equipment',
            field=models.ManyToManyField(to='equipments.Equip'),
        ),
        migrations.AddField(
            model_name='globalmesh',
            name='tamiz_1',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='globalmesh',
            name='tamiz_1_1o2',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='globalmesh',
            name='tamiz_1o2',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='globalmesh',
            name='tamiz_2',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='globalmesh',
            name='tamiz_2_1o2',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='globalmesh',
            name='tamiz_3',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='globalmesh',
            name='tamiz_3o4',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='globalmesh',
            name='tamiz_3o8',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='globalmesh',
            name='tamiz_4',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='globalmesh',
            name='tamiz_N_10',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='globalmesh',
            name='tamiz_N_100',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='globalmesh',
            name='tamiz_N_140',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='globalmesh',
            name='tamiz_N_16',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='globalmesh',
            name='tamiz_N_20',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='globalmesh',
            name='tamiz_N_200',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='globalmesh',
            name='tamiz_N_30',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='globalmesh',
            name='tamiz_N_4',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='globalmesh',
            name='tamiz_N_40',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='globalmesh',
            name='tamiz_N_50',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='globalmesh',
            name='tamiz_N_60',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='globalmesh',
            name='tamiz_N_8',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='globalmesh',
            name='tamiz_N_80',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='globalmesh',
            name='tamiz_fondo',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='globalmesh',
            name='tool',
            field=models.ManyToManyField(to='tools.Tool'),
        ),
        migrations.AddField(
            model_name='globalmesh',
            name='updated',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
