# Generated by Django 2.2.5 on 2019-10-19 00:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ReferencePerson',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(choices=[('NN', 'Ninguna'), ('O', 'Operario'), ('T', 'Técnico'), ('I', 'Ingeniero'), ('M', 'Magister')], default='NN', max_length=5)),
                ('name', models.CharField(max_length=50)),
                ('dni', models.CharField(max_length=50)),
                ('phone', models.CharField(max_length=20)),
                ('ClientProfile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.ClientProfile')),
            ],
        ),
    ]
