# Generated by Django 2.2.5 on 2019-10-23 02:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reference_person', '0003_auto_20191022_2117'),
    ]

    operations = [
        migrations.AlterField(
            model_name='referenceperson',
            name='dni',
            field=models.BigIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='referenceperson',
            name='phone',
            field=models.BigIntegerField(blank=True, null=True),
        ),
    ]
