# Generated by Django 2.2.5 on 2019-10-23 02:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reference_person', '0004_auto_20191022_2118'),
    ]

    operations = [
        migrations.AlterField(
            model_name='referenceperson',
            name='title',
            field=models.CharField(max_length=5),
        ),
    ]
