# Generated by Django 2.2.5 on 2019-10-23 03:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reference_person', '0005_auto_20191022_2125'),
    ]

    operations = [
        migrations.RenameField(
            model_name='referenceperson',
            old_name='ClientProfile',
            new_name='client_profile',
        ),
    ]
