# Generated by Django 2.2.5 on 2019-10-23 23:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reference_person', '0006_auto_20191022_2243'),
    ]

    operations = [
        migrations.AlterField(
            model_name='referenceperson',
            name='title',
            field=models.CharField(max_length=10),
        ),
    ]
