# Generated by Django 2.2.5 on 2020-03-09 03:26

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Equip',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='Maquina Compresora', max_length=50)),
                ('shop_day', models.DateField(blank=True, null=True)),
                ('last_maintenance_day', models.DateField(blank=True, null=True)),
                ('next_maintenance_day', models.DateField(blank=True, null=True)),
                ('maintenance_done', models.BooleanField(default=False)),
                ('use', models.IntegerField(default=0)),
            ],
        ),
    ]
