# Generated by Django 2.2.5 on 2019-10-09 03:34

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Thesis',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150)),
                ('start_day', models.DateField(default=datetime.datetime.now)),
                ('finish_day', models.DateField()),
                ('duration', models.IntegerField(editable=False)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('bach_profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.BachProfile')),
            ],
        ),
    ]
