# Generated by Django 2.2.5 on 2019-10-19 00:53

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('course', '0001_initial'),
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Thesis',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=300)),
                ('line', models.CharField(choices=[('NN', 'Ninguna'), ('TC', 'Agregados'), ('S', 'Geotecnia'), ('MC', 'Mecánica de Materiales'), ('TM', 'Tecnologías Modernas')], default='NN', max_length=5)),
                ('start_day', models.DateField(default=datetime.datetime.now)),
                ('finish_day', models.DateField()),
                ('duration', models.IntegerField(editable=False)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('adviser', models.ManyToManyField(to='accounts.TeacherProfile')),
                ('bach_profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.BachProfile')),
                ('course', models.ManyToManyField(to='course.Course')),
            ],
        ),
    ]
