# Generated by Django 2.2.5 on 2019-10-23 17:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('thesis', '0002_auto_20191021_0911'),
    ]

    operations = [
        migrations.AlterField(
            model_name='thesis',
            name='line',
            field=models.CharField(max_length=30),
        ),
    ]
