# Generated by Django 2.2.5 on 2019-10-09 03:34

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('equipments', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PiceBreak',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='Rotura de Testigo de Concreto', max_length=50)),
                ('code', models.CharField(editable=False, max_length=255, unique=True)),
                ('fc_esp', models.FloatField(default=280.0)),
                ('fecha_vaciado', models.DateField()),
                ('fecha_rotura', models.DateField(default=datetime.datetime.now)),
                ('edad', models.IntegerField(editable=False)),
                ('diameter_esp', models.FloatField(blank=True, choices=[(2, '2 Inch'), (4, '4 Inch'), (6, '6 Inch')], null=True)),
                ('diameter_1', models.FloatField(blank=True, null=True)),
                ('diameter_2', models.FloatField(blank=True, null=True)),
                ('area', models.FloatField(editable=False)),
                ('h', models.FloatField(default=15.0)),
                ('F', models.FloatField()),
                ('fc', models.FloatField(editable=False)),
                ('fc_175', models.FloatField(editable=False)),
                ('fc_210', models.FloatField(editable=False)),
                ('fc_280', models.FloatField(editable=False)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('equipment', models.ManyToManyField(to='equipments.Equip')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
