# Generated by Django 2.2.5 on 2019-10-20 23:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tests_concrete', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='picebreak',
            old_name='fecha_rotura',
            new_name='brek_data',
        ),
        migrations.RenameField(
            model_name='picebreak',
            old_name='edad',
            new_name='duration',
        ),
        migrations.RenameField(
            model_name='picebreak',
            old_name='fecha_vaciado',
            new_name='poured_data',
        ),
        migrations.RemoveField(
            model_name='picebreak',
            name='h',
        ),
        migrations.AlterField(
            model_name='picebreak',
            name='fc_esp',
            field=models.FloatField(),
        ),
    ]
