# Generated by Django 2.2.5 on 2020-06-07 02:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tests_concrete', '0002_auto_20200605_2151'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pice',
            name='fc_175',
        ),
        migrations.RemoveField(
            model_name='pice',
            name='fc_210',
        ),
        migrations.RemoveField(
            model_name='pice',
            name='fc_280',
        ),
    ]
