# Generated by Django 2.2.5 on 2019-10-20 23:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tests_concrete', '0002_auto_20191020_1826'),
    ]

    operations = [
        migrations.RenameField(
            model_name='picebreak',
            old_name='brek_data',
            new_name='break_data',
        ),
        migrations.AddField(
            model_name='picebreak',
            name='h',
            field=models.FloatField(default=15.0),
        ),
    ]
