# Generated by Django 2.2.5 on 2019-10-21 00:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tests_concrete', '0003_auto_20191020_1827'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='picebreak',
            name='h',
        ),
    ]
