# Generated by Django 2.2.5 on 2020-06-07 03:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tests_concrete', '0003_auto_20200606_2129'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='prism',
            name='fc_175',
        ),
        migrations.RemoveField(
            model_name='prism',
            name='fc_210',
        ),
        migrations.RemoveField(
            model_name='prism',
            name='fc_280',
        ),
    ]
