# Generated by Django 2.2.5 on 2019-10-21 01:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tests_concrete', '0004_remove_picebreak_h'),
    ]

    operations = [
        migrations.AlterField(
            model_name='picebreak',
            name='diameter_esp',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
