# Generated by Django 2.2.5 on 2020-06-07 16:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tests_concrete', '0004_auto_20200606_2237'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='diamondpice',
            name='fc_175',
        ),
        migrations.RemoveField(
            model_name='diamondpice',
            name='fc_210',
        ),
        migrations.RemoveField(
            model_name='diamondpice',
            name='fc_280',
        ),
    ]
