# Generated by Django 2.2.5 on 2020-06-07 16:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tests_concrete', '0005_auto_20200607_1106'),
    ]

    operations = [
        migrations.AddField(
            model_name='diamondpice',
            name='check_per',
            field=models.BooleanField(default=True),
        ),
    ]
