# Generated by Django 2.2.5 on 2019-10-25 22:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tests_concrete', '0005_auto_20191020_2053'),
    ]

    operations = [
        migrations.RenameField(
            model_name='picebreak',
            old_name='ref_person',
            new_name='reference_person',
        ),
    ]
