# Generated by Django 2.2.5 on 2019-10-26 15:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tests_concrete', '0006_auto_20191025_1749'),
    ]

    operations = [
        migrations.AlterField(
            model_name='picebreak',
            name='diameter_esp',
            field=models.FloatField(blank=True, choices=[(0, False), (2, '2 Inch'), (4, '4 Inch'), (6, '6 Inch')], null=True),
        ),
        migrations.AlterField(
            model_name='picebreak',
            name='fc_esp',
            field=models.FloatField(default=280),
        ),
    ]
