# Generated by Django 2.2.5 on 2020-06-07 17:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tests_concrete', '0006_diamondpice_check_per'),
    ]

    operations = [
        migrations.AlterField(
            model_name='diamondpice',
            name='check_per',
            field=models.BooleanField(),
        ),
    ]
