# Generated by Django 2.2.5 on 2019-10-27 00:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tests_concrete', '0007_auto_20191026_1053'),
    ]

    operations = [
        migrations.AlterField(
            model_name='picebreak',
            name='diameter_esp',
            field=models.FloatField(blank=True, choices=[(2, '2 Inch'), (4, '4 Inch'), (6, '6 Inch')], null=True),
        ),
    ]
