# Generated by Django 2.2.5 on 2020-06-08 22:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tests_concrete', '0007_auto_20200607_1228'),
    ]

    operations = [
        migrations.AddField(
            model_name='pice',
            name='check_per',
            field=models.BooleanField(default=True),
            preserve_default=False,
        ),
    ]
