# Generated by Django 2.2.5 on 2020-06-08 23:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tests_concrete', '0008_pice_check_per'),
    ]

    operations = [
        migrations.AddField(
            model_name='prism',
            name='check_per',
            field=models.BooleanField(default=True),
            preserve_default=False,
        ),
    ]
