# Generated by Django 2.2.5 on 2019-10-27 16:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tests_concrete', '0008_auto_20191026_1957'),
    ]

    operations = [
        migrations.AddField(
            model_name='picebreak',
            name='element',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
