# Generated by Django 2.2.5 on 2019-10-28 02:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0002_auto_20191018_2305'),
        ('tests_concrete', '0009_picebreak_element'),
    ]

    operations = [
        migrations.AddField(
            model_name='picebreak',
            name='course',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='course.Course'),
        ),
    ]
