# Generated by Django 2.2.5 on 2019-10-28 02:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('reference_person', '0007_auto_20191023_1837'),
        ('construction', '0003_remove_construction_reference'),
        ('tests_concrete', '0010_picebreak_course'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='picebreak',
            name='construction',
        ),
        migrations.AddField(
            model_name='picebreak',
            name='construction',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='construction.Construction'),
        ),
        migrations.RemoveField(
            model_name='picebreak',
            name='reference_person',
        ),
        migrations.AddField(
            model_name='picebreak',
            name='reference_person',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='reference_person.ReferencePerson'),
        ),
    ]
