# Generated by Django 2.2.5 on 2019-10-28 23:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tests_concrete', '0012_groutdicebreak'),
    ]

    operations = [
        migrations.RenameField(
            model_name='groutdicebreak',
            old_name='fecha_rotura',
            new_name='break_data',
        ),
        migrations.RenameField(
            model_name='groutdicebreak',
            old_name='fecha_vaciado',
            new_name='poured_data',
        ),
    ]
