# Generated by Django 2.2.5 on 2019-10-29 16:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tests_concrete', '0013_auto_20191028_1859'),
    ]

    operations = [
        migrations.RenameField(
            model_name='groutdicebreak',
            old_name='edad',
            new_name='duration',
        ),
    ]
