# Generated by Django 2.2.5 on 2019-10-29 16:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tests_concrete', '0015_groutdicebreak_fc_mpa'),
    ]

    operations = [
        migrations.AlterField(
            model_name='groutdicebreak',
            name='fc_MPa',
            field=models.FloatField(editable=False),
        ),
    ]
