# Generated by Django 2.2.5 on 2019-10-29 18:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tests_concrete', '0016_auto_20191029_1121'),
    ]

    operations = [
        migrations.CreateModel(
            name='PaverBreak',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.AlterField(
            model_name='picebreak',
            name='name',
            field=models.CharField(default='Rotura Testigo Concreto', max_length=50),
        ),
    ]
