# Generated by Django 2.2.5 on 2019-10-29 18:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tests_concrete', '0017_auto_20191029_1325'),
    ]

    operations = [
        migrations.DeleteModel(
            name='PaverBreak',
        ),
    ]
