# Generated by Django 2.2.5 on 2019-10-30 15:41

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('reference_person', '0007_auto_20191023_1837'),
        ('construction', '0003_remove_construction_reference'),
        ('equipments', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('tools', '0001_initial'),
        ('course', '0002_auto_20191018_2305'),
        ('tests_concrete', '0020_limedicebreak'),
    ]

    operations = [
        migrations.CreateModel(
            name='LimePiceBreak',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='Rotura Testigo Cal', max_length=50)),
                ('element', models.CharField(blank=True, max_length=50, null=True)),
                ('code', models.CharField(editable=False, max_length=255, unique=True)),
                ('fc_esp', models.FloatField(default=280)),
                ('poured_data', models.DateField()),
                ('break_data', models.DateField(default=datetime.datetime.now)),
                ('duration', models.IntegerField(editable=False)),
                ('diameter_1', models.FloatField(blank=True, null=True)),
                ('diameter_2', models.FloatField(blank=True, null=True)),
                ('area', models.FloatField(editable=False)),
                ('F', models.FloatField()),
                ('fc', models.FloatField(editable=False)),
                ('fc_MPa', models.FloatField(editable=False)),
                ('fc_175', models.FloatField(editable=False)),
                ('fc_210', models.FloatField(editable=False)),
                ('fc_280', models.FloatField(editable=False)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('construction', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='construction.Construction')),
                ('course', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='course.Course')),
                ('equipment', models.ManyToManyField(to='equipments.Equip')),
                ('reference_person', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='reference_person.ReferencePerson')),
                ('tool', models.ManyToManyField(to='tools.Tool')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
