# Generated by Django 2.2.5 on 2019-10-30 16:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tests_concrete', '0021_limepicebreak'),
    ]

    operations = [
        migrations.AlterField(
            model_name='limepicebreak',
            name='diameter_1',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='limepicebreak',
            name='diameter_2',
            field=models.FloatField(),
        ),
    ]
