# Generated by Django 2.2.5 on 2019-11-04 18:51

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tests_concrete', '0023_diamondpicebreak'),
    ]

    operations = [
        migrations.AddField(
            model_name='picebreak',
            name='reception_data',
            field=models.DateField(blank=True, default=datetime.datetime.now, null=True),
        ),
    ]
