# Generated by Django 2.2.5 on 2019-11-05 00:24

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tests_concrete', '0026_limepicebreak_reception_data'),
    ]

    operations = [
        migrations.AddField(
            model_name='limedicebreak',
            name='reception_data',
            field=models.DateField(blank=True, default=datetime.datetime.now, null=True),
        ),
    ]
