# Generated by Django 2.2.5 on 2019-12-17 05:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tests_concrete', '0028_groutdicebreak_reception_data'),
    ]

    operations = [
        migrations.RenameField(
            model_name='picebreak',
            old_name='break_data',
            new_name='break_date',
        ),
        migrations.RenameField(
            model_name='picebreak',
            old_name='duration',
            new_name='dilate',
        ),
        migrations.RenameField(
            model_name='picebreak',
            old_name='element',
            new_name='element_name',
        ),
        migrations.RenameField(
            model_name='picebreak',
            old_name='poured_data',
            new_name='poured_date',
        ),
        migrations.RenameField(
            model_name='picebreak',
            old_name='reception_data',
            new_name='sampling_date',
        ),
        migrations.RemoveField(
            model_name='picebreak',
            name='F',
        ),
        migrations.RemoveField(
            model_name='picebreak',
            name='area',
        ),
        migrations.RemoveField(
            model_name='picebreak',
            name='diameter_1',
        ),
        migrations.RemoveField(
            model_name='picebreak',
            name='diameter_2',
        ),
        migrations.RemoveField(
            model_name='picebreak',
            name='diameter_esp',
        ),
        migrations.RemoveField(
            model_name='picebreak',
            name='fc',
        ),
        migrations.RemoveField(
            model_name='picebreak',
            name='fc_175',
        ),
        migrations.RemoveField(
            model_name='picebreak',
            name='fc_210',
        ),
        migrations.RemoveField(
            model_name='picebreak',
            name='fc_280',
        ),
        migrations.RemoveField(
            model_name='picebreak',
            name='fc_MPa',
        ),
        migrations.AlterField(
            model_name='picebreak',
            name='name',
            field=models.CharField(default='Rotura Testigo', max_length=50),
        ),
    ]
