# Generated by Django 2.2.5 on 2019-12-17 05:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tests_concrete', '0029_auto_20191217_0005'),
    ]

    operations = [
        migrations.AddField(
            model_name='picebreak',
            name='pice_type',
            field=models.CharField(choices=[('CONCRETO', 'Testigo de Concreto'), ('CAL', 'Testigo de Cal')], default='CONCRETO', max_length=10),
        ),
    ]
