# Generated by Django 2.2.5 on 2019-12-17 05:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('equipments', '0001_initial'),
        ('tools', '0001_initial'),
        ('tests_concrete', '0030_picebreak_pice_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='Pice',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('D_1', models.FloatField()),
                ('D_2', models.FloatField()),
                ('avg_area', models.FloatField(editable=False)),
                ('load', models.FloatField()),
                ('fc', models.FloatField(editable=False)),
                ('fc_MPa', models.FloatField(editable=False)),
                ('fc_175', models.FloatField(editable=False)),
                ('fc_210', models.FloatField(editable=False)),
                ('fc_280', models.FloatField(editable=False)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('equipment', models.ManyToManyField(to='equipments.Equip')),
                ('pice_break', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tests_concrete.PiceBreak')),
                ('tool', models.ManyToManyField(to='tools.Tool')),
            ],
        ),
    ]
