# Generated by Django 2.2.5 on 2019-12-17 17:04

import datetime
from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('tests_concrete', '0031_pice'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='picebreak',
            name='break_date',
        ),
        migrations.RemoveField(
            model_name='picebreak',
            name='dilate',
        ),
        migrations.RemoveField(
            model_name='picebreak',
            name='poured_date',
        ),
        migrations.AddField(
            model_name='pice',
            name='break_date',
            field=models.DateField(default=datetime.datetime.now),
        ),
        migrations.AddField(
            model_name='pice',
            name='dilate',
            field=models.IntegerField(default=1, editable=False),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='pice',
            name='poured_date',
            field=models.DateField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='picebreak',
            name='element_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
