# Generated by Django 2.2.5 on 2019-12-17 18:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tests_concrete', '0032_auto_20191217_1204'),
    ]

    operations = [
        migrations.RenameField(
            model_name='pice',
            old_name='avg_area',
            new_name='area',
        ),
    ]
