# Generated by Django 2.2.5 on 2019-12-17 18:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tests_concrete', '0033_auto_20191217_1309'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pice',
            name='break_date',
            field=models.DateField(),
        ),
    ]
