# Generated by Django 2.2.5 on 2019-12-18 01:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tests_concrete', '0034_auto_20191217_1338'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='picebreak',
            name='element_name',
        ),
        migrations.AddField(
            model_name='pice',
            name='element_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
