# Generated by Django 2.2.5 on 2019-12-18 16:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tests_concrete', '0036_prism_prismbreak'),
    ]

    operations = [
        migrations.RenameField(
            model_name='prism',
            old_name='pice_break',
            new_name='prism_break',
        ),
    ]
