# Generated by Django 2.2.5 on 2019-12-19 22:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tools', '0001_initial'),
        ('equipments', '0001_initial'),
        ('tests_concrete', '0037_auto_20191218_1154'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='diamondpicebreak',
            name='D',
        ),
        migrations.RemoveField(
            model_name='diamondpicebreak',
            name='F',
        ),
        migrations.RemoveField(
            model_name='diamondpicebreak',
            name='L',
        ),
        migrations.RemoveField(
            model_name='diamondpicebreak',
            name='area',
        ),
        migrations.RemoveField(
            model_name='diamondpicebreak',
            name='break_data',
        ),
        migrations.RemoveField(
            model_name='diamondpicebreak',
            name='correction',
        ),
        migrations.RemoveField(
            model_name='diamondpicebreak',
            name='duration',
        ),
        migrations.RemoveField(
            model_name='diamondpicebreak',
            name='element',
        ),
        migrations.RemoveField(
            model_name='diamondpicebreak',
            name='extraction_data',
        ),
        migrations.RemoveField(
            model_name='diamondpicebreak',
            name='factor_ld',
        ),
        migrations.RemoveField(
            model_name='diamondpicebreak',
            name='fc',
        ),
        migrations.RemoveField(
            model_name='diamondpicebreak',
            name='fc_175',
        ),
        migrations.RemoveField(
            model_name='diamondpicebreak',
            name='fc_210',
        ),
        migrations.RemoveField(
            model_name='diamondpicebreak',
            name='fc_280',
        ),
        migrations.RemoveField(
            model_name='diamondpicebreak',
            name='fc_MPa',
        ),
        migrations.AddField(
            model_name='diamondpicebreak',
            name='sampling_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.CreateModel(
            name='DiamondPice',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('extraction_date', models.DateField()),
                ('break_date', models.DateField()),
                ('dilate', models.IntegerField(editable=False)),
                ('element_name', models.CharField(blank=True, max_length=100, null=True)),
                ('D', models.FloatField()),
                ('L', models.FloatField()),
                ('factor_ld', models.FloatField(editable=False)),
                ('area', models.FloatField(editable=False)),
                ('correction', models.FloatField(editable=False)),
                ('load', models.FloatField()),
                ('fc', models.FloatField(editable=False)),
                ('fc_MPa', models.FloatField(editable=False)),
                ('fc_175', models.FloatField(editable=False)),
                ('fc_210', models.FloatField(editable=False)),
                ('fc_280', models.FloatField(editable=False)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('diamond_pice_break', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tests_concrete.DiamondPiceBreak')),
                ('equipment', models.ManyToManyField(to='equipments.Equip')),
                ('tool', models.ManyToManyField(to='tools.Tool')),
            ],
        ),
    ]
