# Generated by Django 2.2.5 on 2020-01-20 15:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tests_concrete', '0039_auto_20191219_2215'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pice',
            name='poured_date',
            field=models.DateField(db_column='Fecha de Vaciado'),
        ),
        migrations.AlterField(
            model_name='picebreak',
            name='pice_type',
            field=models.CharField(choices=[('CONCRETO', 'Testigo de Concreto'), ('CAL', 'Testigo de Cal')], db_column='Tipo de Probeta', default='CONCRETO', max_length=10),
        ),
        migrations.AlterModelTable(
            name='pice',
            table='Probetas',
        ),
        migrations.AlterModelTable(
            name='picebreak',
            table='Ensayos de Probetas',
        ),
    ]
