# Generated by Django 2.2.5 on 2020-01-20 15:53

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tests_concrete', '0040_auto_20200120_1017'),
    ]

    operations = [
        migrations.AlterField(
            model_name='picebreak',
            name='user',
            field=models.ForeignKey(db_column='Usuario', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
