# Generated by Django 2.2.5 on 2020-01-20 16:08

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tests_concrete', '0041_auto_20200120_1053'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pice',
            name='D_1',
            field=models.FloatField(db_column='Diametro 1'),
        ),
        migrations.AlterField(
            model_name='pice',
            name='D_2',
            field=models.FloatField(db_column='Diametro 2'),
        ),
        migrations.AlterField(
            model_name='pice',
            name='area',
            field=models.FloatField(db_column='Area', editable=False),
        ),
        migrations.AlterField(
            model_name='pice',
            name='break_date',
            field=models.DateField(db_column='Fecha de Rotura'),
        ),
        migrations.AlterField(
            model_name='pice',
            name='created',
            field=models.DateTimeField(auto_now_add=True, db_column='Creado'),
        ),
        migrations.AlterField(
            model_name='pice',
            name='dilate',
            field=models.IntegerField(db_column='Diferencia entre Fechas', editable=False),
        ),
        migrations.AlterField(
            model_name='pice',
            name='element_name',
            field=models.CharField(blank=True, db_column='Nombre del Elemento', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='pice',
            name='equipment',
            field=models.ManyToManyField(db_column='Equipos', to='equipments.Equip'),
        ),
        migrations.AlterField(
            model_name='pice',
            name='fc',
            field=models.FloatField(db_column='Esfuerzo', editable=False),
        ),
        migrations.AlterField(
            model_name='pice',
            name='fc_175',
            field=models.FloatField(db_column='Esfuerzo a 175', editable=False),
        ),
        migrations.AlterField(
            model_name='pice',
            name='fc_210',
            field=models.FloatField(db_column='Esfuerzo a 210', editable=False),
        ),
        migrations.AlterField(
            model_name='pice',
            name='fc_280',
            field=models.FloatField(db_column='Esfuerzo a 280', editable=False),
        ),
        migrations.AlterField(
            model_name='pice',
            name='fc_MPa',
            field=models.FloatField(db_column='Esfuerzo MPa', editable=False),
        ),
        migrations.AlterField(
            model_name='pice',
            name='load',
            field=models.FloatField(db_column='Carga'),
        ),
        migrations.AlterField(
            model_name='pice',
            name='pice_break',
            field=models.ForeignKey(db_column='Ensayos de Probetas', on_delete=django.db.models.deletion.CASCADE, to='tests_concrete.PiceBreak'),
        ),
        migrations.AlterField(
            model_name='pice',
            name='tool',
            field=models.ManyToManyField(db_column='Herramientas', to='tools.Tool'),
        ),
        migrations.AlterField(
            model_name='pice',
            name='updated',
            field=models.DateTimeField(auto_now=True, db_column='Actualizado'),
        ),
        migrations.AlterField(
            model_name='picebreak',
            name='code',
            field=models.CharField(db_column='Codigo', editable=False, max_length=255, unique=True),
        ),
        migrations.AlterField(
            model_name='picebreak',
            name='construction',
            field=models.ForeignKey(blank=True, db_column='Construccion', null=True, on_delete=django.db.models.deletion.SET_NULL, to='construction.Construction'),
        ),
        migrations.AlterField(
            model_name='picebreak',
            name='course',
            field=models.ForeignKey(blank=True, db_column='Curso', null=True, on_delete=django.db.models.deletion.SET_NULL, to='course.Course'),
        ),
        migrations.AlterField(
            model_name='picebreak',
            name='created',
            field=models.DateTimeField(auto_now_add=True, db_column='Creado'),
        ),
        migrations.AlterField(
            model_name='picebreak',
            name='equipment',
            field=models.ManyToManyField(db_column='Equipos', to='equipments.Equip'),
        ),
        migrations.AlterField(
            model_name='picebreak',
            name='fc_esp',
            field=models.FloatField(db_column='Esfuerzo Especificado', default=280),
        ),
        migrations.AlterField(
            model_name='picebreak',
            name='name',
            field=models.CharField(db_column='Nombre Propio', default='Rotura Testigo', max_length=50),
        ),
        migrations.AlterField(
            model_name='picebreak',
            name='reference_person',
            field=models.ForeignKey(blank=True, db_column='Persona de Referencia', null=True, on_delete=django.db.models.deletion.SET_NULL, to='reference_person.ReferencePerson'),
        ),
        migrations.AlterField(
            model_name='picebreak',
            name='sampling_date',
            field=models.DateField(blank=True, db_column='Fecha de Muestreo', default=datetime.datetime.now, null=True),
        ),
        migrations.AlterField(
            model_name='picebreak',
            name='tool',
            field=models.ManyToManyField(db_column='Herramientas', to='tools.Tool'),
        ),
        migrations.AlterField(
            model_name='picebreak',
            name='updated',
            field=models.DateTimeField(auto_now=True, db_column='Actualizado'),
        ),
    ]
