# Generated by Django 2.2.5 on 2020-01-20 17:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tests_concrete', '0042_auto_20200120_1108'),
    ]

    operations = [
        migrations.AlterField(
            model_name='picebreak',
            name='tool',
            field=models.ManyToManyField(db_column='Herramientas', to='tools.Tool', verbose_name='Herramientas Usadas'),
        ),
    ]
