# Generated by Django 2.2.5 on 2020-01-20 17:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tests_concrete', '0043_auto_20200120_1241'),
    ]

    operations = [
        migrations.AlterField(
            model_name='picebreak',
            name='tool',
            field=models.ManyToManyField(db_column='Herramientas', to='tools.Tool'),
        ),
    ]
