# Generated by Django 2.2.5 on 2020-01-20 18:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tests_concrete', '0044_auto_20200120_1252'),
    ]

    operations = [
        migrations.AlterField(
            model_name='picebreak',
            name='tool',
            field=models.ManyToManyField(db_column='Herramientas', db_table='Ensayo de Probetas Uso de Herramientas', to='tools.Tool'),
        ),
    ]
