# Generated by Django 2.2.5 on 2020-01-20 18:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tests_concrete', '0045_auto_20200120_1306'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pice',
            name='equipment',
            field=models.ManyToManyField(db_column='Equipos', db_table='Probetas Uso de Equipos', to='equipments.Equip'),
        ),
        migrations.AlterField(
            model_name='pice',
            name='tool',
            field=models.ManyToManyField(db_column='Herramientas', db_table='Probetas Uso de Herramientas', to='tools.Tool'),
        ),
        migrations.AlterField(
            model_name='picebreak',
            name='equipment',
            field=models.ManyToManyField(db_column='Equipos', db_table='Ensayo de Probetas Uso de Equipos', to='equipments.Equip'),
        ),
    ]
