# Generated by Django 2.2.5 on 2020-01-20 18:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tests_concrete', '0046_auto_20200120_1312'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pice',
            name='equipment',
            field=models.ManyToManyField(db_column='Equipos', db_table='Testigos - Uso de Equipos', to='equipments.Equip'),
        ),
        migrations.AlterField(
            model_name='pice',
            name='pice_break',
            field=models.ForeignKey(db_column='Ensayos de Testigos', on_delete=django.db.models.deletion.CASCADE, to='tests_concrete.PiceBreak'),
        ),
        migrations.AlterField(
            model_name='pice',
            name='tool',
            field=models.ManyToManyField(db_column='Herramientas', db_table='Testigos - Uso de Herramientas', to='tools.Tool'),
        ),
        migrations.AlterField(
            model_name='picebreak',
            name='equipment',
            field=models.ManyToManyField(db_column='Equipos', db_table='Ensayo de Testigos - Uso de Equipos', to='equipments.Equip'),
        ),
        migrations.AlterField(
            model_name='picebreak',
            name='pice_type',
            field=models.CharField(choices=[('CONCRETO', 'Testigo de Concreto'), ('CAL', 'Testigo de Cal')], db_column='Tipo de Testigo', default='CONCRETO', max_length=10),
        ),
        migrations.AlterField(
            model_name='picebreak',
            name='tool',
            field=models.ManyToManyField(db_column='Herramientas', db_table='Ensayo de Testigos - Uso de Herramientas', to='tools.Tool'),
        ),
        migrations.AlterModelTable(
            name='pice',
            table='Testigos',
        ),
        migrations.AlterModelTable(
            name='picebreak',
            table='Ensayos de Testigos',
        ),
    ]
