# Generated by Django 2.2.5 on 2019-10-23 01:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('construction', '0002_auto_20191021_2200'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='construction',
            name='reference',
        ),
    ]
