# Generated by Django 2.2.5 on 2020-01-20 16:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tools', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='tool',
            table='Herramientas',
        ),
    ]
