# Generated by Django 2.2.5 on 2020-01-20 17:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tools', '0002_auto_20200120_1125'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='tool',
            options={'verbose_name': 'Herramientas'},
        ),
    ]
