# Generated by Django 2.2.5 on 2020-06-09 17:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tests_material', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='parallelperpendicular',
            name='name_element',
            field=models.CharField(default=None, max_length=40),
            preserve_default=False,
        ),
    ]
