# Generated by Django 2.2.5 on 2020-06-25 21:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tests_material', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='warping',
            name='name_element',
            field=models.CharField(default='nombre x', max_length=50),
            preserve_default=False,
        ),
    ]
