# Generated by Django 2.2.5 on 2019-10-28 20:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tests_material', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='groutdicebreak',
            name='equipment',
        ),
    ]
