# Generated by Django 2.2.5 on 2019-10-28 21:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tests_material', '0002_remove_groutdicebreak_equipment'),
    ]

    operations = [
        migrations.DeleteModel(
            name='GroutDiceBreak',
        ),
    ]
