# Generated by Django 2.2.5 on 2020-06-09 18:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tests_material', '0002_parallelperpendicular_name_element'),
    ]

    operations = [
        migrations.AddField(
            model_name='masonry',
            name='element_name',
            field=models.CharField(default=None, max_length=40),
            preserve_default=False,
        ),
    ]
