# Generated by Django 2.2.5 on 2019-09-28 21:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tests_material', '0002_auto_20190928_1612'),
    ]

    operations = [
        migrations.AlterField(
            model_name='groutdicebreak',
            name='fecha_rotura',
            field=models.DateField(auto_now_add=True),
        ),
    ]
