# Generated by Django 2.2.5 on 2019-09-28 21:20

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tests_material', '0003_auto_20190928_1616'),
    ]

    operations = [
        migrations.AlterField(
            model_name='groutdicebreak',
            name='fecha_rotura',
            field=models.DateField(default=datetime.datetime.now),
        ),
    ]
