# Generated by Django 2.2.5 on 2020-06-26 15:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tests_material', '0004_abssatucoeff_name_element'),
    ]

    operations = [
        migrations.AddField(
            model_name='suction',
            name='name_element',
            field=models.CharField(default='ladrillo', max_length=50),
            preserve_default=False,
        ),
    ]
