# Generated by Django 2.2.5 on 2019-12-05 16:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tests_material', '0004_abssatucoeff_bricktype_compretionbrick_densityvoids_suction_variationdimensions_warping'),
    ]

    operations = [
        migrations.RenameField(
            model_name='compretionbrick',
            old_name='compression_resistance',
            new_name='fc',
        ),
        migrations.AddField(
            model_name='compretionbrick',
            name='fc_MPa',
            field=models.FloatField(default=0, editable=False),
            preserve_default=False,
        ),
    ]
