# Generated by Django 2.2.5 on 2019-12-06 01:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tests_material', '0005_auto_20191205_1110'),
    ]

    operations = [
        migrations.RenameField(
            model_name='bricktype',
            old_name='delate',
            new_name='dilate',
        ),
    ]
