# Generated by Django 2.2.5 on 2020-06-26 17:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tests_material', '0006_compretionbrick_name_element'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='masonry',
            name='tp',
        ),
    ]
