# Generated by Django 2.2.5 on 2019-12-07 17:32

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('course', '0002_auto_20191018_2305'),
        ('equipments', '0001_initial'),
        ('construction', '0003_remove_construction_reference'),
        ('tools', '0001_initial'),
        ('reference_person', '0007_auto_20191023_1837'),
        ('tests_material', '0007_auto_20191206_1037'),
    ]

    operations = [
        migrations.CreateModel(
            name='WoodCompression',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='Compresion de Madera', max_length=50)),
                ('name_element', models.CharField(blank=True, max_length=50, null=True)),
                ('wood_name', models.CharField(blank=True, max_length=100, null=True)),
                ('code', models.CharField(editable=False, max_length=255, unique=True)),
                ('sampling_date', models.DateField()),
                ('done_date', models.DateField(default=datetime.datetime.now)),
                ('dilate', models.IntegerField(editable=False)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('construction', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='construction.Construction')),
                ('course', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='course.Course')),
                ('equipment', models.ManyToManyField(to='equipments.Equip')),
                ('reference_person', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='reference_person.ReferencePerson')),
                ('tool', models.ManyToManyField(to='tools.Tool')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='ParallelPerpendicular',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type_compression', models.CharField(choices=[('NINGUNA', 'Ninguna'), ('PARALELO', 'Comprecíon Paralelo a la Fibra'), ('PERPENDICULAR', 'Compreción Perpendicular a la Fibra')], default='NINGUNA', max_length=40)),
                ('length_1', models.FloatField()),
                ('width_1', models.FloatField()),
                ('area_1', models.FloatField(editable=False)),
                ('length_2', models.FloatField()),
                ('width_2', models.FloatField(editable=False)),
                ('area_2', models.FloatField()),
                ('avg_pro', models.FloatField(editable=False)),
                ('load', models.FloatField()),
                ('fc', models.FloatField(editable=False)),
                ('fc_MPa', models.FloatField(editable=False)),
                ('equipment', models.ManyToManyField(to='equipments.Equip')),
                ('tool', models.ManyToManyField(to='tools.Tool')),
                ('wood_compression', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tests_material.WoodCompression')),
            ],
        ),
    ]
