# Generated by Django 2.2.5 on 2019-12-07 18:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tests_material', '0009_auto_20191207_1258'),
    ]

    operations = [
        migrations.RenameField(
            model_name='parallelperpendicular',
            old_name='avg_pro',
            new_name='average_area',
        ),
    ]
