# Generated by Django 2.2.5 on 2019-12-12 02:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tests_material', '0011_remove_abssatucoeff_wet_weight_hot_24'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='suction',
            name='bar_200',
        ),
    ]
