# Generated by Django 2.2.5 on 2019-12-12 03:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tests_material', '0012_remove_suction_bar_200'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='densityvoids',
            name='bar',
        ),
        migrations.RemoveField(
            model_name='densityvoids',
            name='bar_500',
        ),
    ]
