# Generated by Django 2.2.5 on 2019-12-23 02:29

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('equipments', '0001_initial'),
        ('reference_person', '0007_auto_20191023_1837'),
        ('construction', '0003_remove_construction_reference'),
        ('course', '0002_auto_20191018_2305'),
        ('tools', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('tests_material', '0014_auto_20191211_2222'),
    ]

    operations = [
        migrations.CreateModel(
            name='MasonryCompression',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('brick_type', models.CharField(choices=[('LADRILLO_UNIDAD_HUECA', 'Ladrillo Unidad Hueca'), ('LADRILLO_UNIDAD_SOLIDA', 'Ladrillo Unidad Solida'), ('BLOQUE_UNIDAD_HUECA', 'Bloque Unidad Hueca')], default='LADRILLO_UNIDAD_HUECA', max_length=50)),
                ('name', models.CharField(default='Compresion de Albañileria', max_length=50)),
                ('code', models.CharField(editable=False, max_length=255, unique=True)),
                ('sampling_date', models.DateField(blank=True, default=datetime.datetime.now, null=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('construction', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='construction.Construction')),
                ('course', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='course.Course')),
                ('equipment', models.ManyToManyField(to='equipments.Equip')),
                ('reference_person', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='reference_person.ReferencePerson')),
                ('tool', models.ManyToManyField(to='tools.Tool')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Masonry',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('poured_date', models.DateField()),
                ('break_date', models.DateField()),
                ('dilate', models.IntegerField(editable=False)),
                ('element_name', models.CharField(blank=True, max_length=100, null=True)),
                ('L', models.FloatField()),
                ('A', models.FloatField()),
                ('hp', models.FloatField()),
                ('tp', models.FloatField()),
                ('hp_tp', models.FloatField(editable=False)),
                ('correction', models.FloatField(editable=False)),
                ('area', models.FloatField(editable=False)),
                ('load', models.FloatField()),
                ('fc', models.FloatField(editable=False)),
                ('fc_MPa', models.FloatField(editable=False)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('equipment', models.ManyToManyField(to='equipments.Equip')),
                ('masonry_compression', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tests_material.MasonryCompression')),
                ('tool', models.ManyToManyField(to='tools.Tool')),
            ],
        ),
    ]
