# Generated by Django 2.2.5 on 2019-12-23 02:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tests_material', '0015_masonry_masonrycompression'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='masonry',
            name='element_name',
        ),
        migrations.AddField(
            model_name='masonrycompression',
            name='element_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
